### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by j88per** [gobuffalo/gobuffalo#37]
I'm starting out in go for the weekend, just testing it out but the docs seem a little grey.  I'm not entirely sure how you get from this

$ go get -u github.com/gobuffalo/buffalo/buffalo

to this

$ cd $GOPATH/src/github.com/$USER/
$ # Make sure $GOPATH/bin is in your $PATH, then:
$ buffalo new

I created a brand new ubuntu 16 container, go 1.6 installed, tested with the BS hello stuff and it works fine.  I run the go get command above, it thinks for a while, after a bit, I get a src folder.  Yay.  But there is no buffalo command in GOROOT, GOPATH or anywhere for that matter.  Also, cd $GOPATH/src/github.com/$USER/ doesn't exist - How does $USER get created?  The instructions don't tell me to do that, so?

I know go is working.  So how does that $USER path get created? and where is buffalo supposed to get installed because it isn't in $GOROOT/bin  find / -type f -name buffalo comes back null.

**Comment by markbates** [comment]
First, let me say that documentation PRs are always welcome, especially by those who run into issues, you're in the best position to make the documentation clearer. :)

Now, to answer your questions. First, I would update the version of Go you're using. Buffalo requires `1.7` and the latest version of Go is `1.8.1`. Your version is over a year old, so best to get that updated. 

Next, Go binaries get installed into `$GOPATH/bin`, not `$GOROOT/bin`, so you'll want to check there. Because you are using an old version of Go, that Buffalo doesn't support, the binary won't have built, so it won't be there. Update your Go, and try the `go get` again.

Next, `$USER` is common Linux shorthand for your user account. Most people do their work in Go under `$GOPATH/src/github.com/<your GitHub username here/`. That's optional, but it's the common practice for developing Go applications. Regardless of where you decide to do your work, *all* Go code *must* be under `$GOPATH/src` that is a Go requirement, and no way around it.

I hope all this helps. Good luck!

**Comment by danielsousaio** [comment]
I would recommend running with the -v flag to see if any error is presented:

go get -u -v github.com/gobuffalo/buffalo/buffalo

Also you can take a look at this [PR#38](https://github.com/gobuffalo/gobuffalo/pull/38), added information about dependecies.

**Comment by markbates** [comment]
Thanks to @danielsousaio the installation, and requirements, section of the docs has greatly improved! http://gobuffalo.io/docs/getting-started#installation

**Comment by j88per** [comment]
My issue was that there is nothing between those two statements in the documentation to suggest how/where/why $USER gets created.  Is it created automatically?  Is it up to the person trying to follow the directions to create it?  Does it get created for you?  Assumptions like these make it difficult for someone new to follow along and get into something, ie making adoption difficult.  

I started using linux in 1993/1994 with slackware, I taught for Sun Microsystems Admin and Cluster, so I'm pretty sure I understand what $USER is, but the docs don't say I should create it.  Even if it's a standard.  As for GOPATH, that's set.  I was able to install the revel framework quickly, along with examples and verify it works.  But I'd like to try this framework and see it work as well.  Following along didn't let me do that, but I'll try again later and see what I can see.  Thanks for the feedback.

**Comment by j88per** [comment]
another issue I've run into is /usr/local is usually protected, and commands such as buffalo can't be generated, unless sudo, then you run into issues of setting up the ENV for root, etc etc etc.  Short term, I just set perms to 777 for the purpose of installing, but it's not really a solution.  

I did get the framework up and running and am looking forward to trying it out. Thanks for the help and I saw the updated docs, super helpful!
