### ISSUE TITLE
markdown style

### ISSUE THREAD

**Issue by d7561985** [gobuffalo/gobuffalo#404]
In document page markdown comments not handled correctly.
example:
> page http://127.0.0.1:3000/en/docs/generators

has no comment style just row text without any style 

copy-paste text on page has markdown code, so i cant past it here. just set it on pastebin - https://pastebin.com/mY8VEy1U

**Comment by lukasschlueter** [comment]
This was caused by cbb3194 (introduced in #403) and has been "fixed" by reverting it in edc392c.

This bug will currently be added again by #405
I will be looking into this but I'm a bit clueless on how to start. It might be a bug directly in https://github.com/gobuffalo/github_flavored_markdown or in e.g. https://github.com/gobuffalo/plush.

Maybe someone can provide directions on how to find the root cause of the bug?
